FROM python:3.11

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip
RUN pip install .[arroyo]

ENV HOME /app

# Use app_xps.py for XPS data processing
CMD ["python", "-m", "src.arroyo_reduction.app_xps"]