authentication:
  # The default is false. Set to true to enable any HTTP client that can
  # connect to _read_. An API key is still required to write.
  allow_anonymous_access: true
  single_user_api_key: ${TILED_SINGLE_USER_API_KEY}
trees:
  - path: /
    tree: catalog
    args:
      uri: "postgresql+asyncpg://${TILED_DB_USER}:${TILED_DB_PW}@${TILED_DB_SERVER}:5432/${TILED_DB_NAME}"
      readable_storage: ["/tiled_storage"]
      writable_storage: "/tiled_storage/writable"
      # This creates the database if it does not exist. This is convenient, but in
      # a horizonally-scaled deployment, this can be a race condition and multiple
      # containers may simultanouesly attempt to create the database.
      # If that is a problem, set this to false, and run:
      #
      # tiled catalog init URI
      #
      # separately.
      init_if_not_exists: true
uvicorn:
  host: 0.0.0.0
  port: 8000
object_cache:
  available_bytes: 0
metrics: 
  prometheus: false